### PR TITLE
Merkle fixes

### PR DESCRIPTION
**Pull request by uncomputable**
Fixes a few things that I noticed about our Merkle roots.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK c798e73efd6827a1f432b2ecfe60735e39d461fc

**Comment by uncomputable** [comment]
Rebased on `master`.

**Review by apoelstra — APPROVED** [review]
ACK 389fb5e87920c78f9dc00d1ee9fad1aa9793c9d5

**Review by sanket1729 — COMMENTED** [review]
ACK 389fb5e87920c78f9dc00d1ee9fad1aa9793c9d5.

**Comment by sanket1729** [comment]
Oops, I had ACKed it, but forgot to submit

**Pull request merged**
