### PR TITLE
Fix jets

### PR DESCRIPTION
**Pull request by uncomputable**
Fix two things to make jets more usable.

### CODE REVIEW

**Comment by uncomputable** [comment]
The `c_jet_env` is useful in generic code over `J: Jet`. It is the only way to transform `J::Environment` to `J::CJetEnvironment`. I use `c_jet_env` inside the web IDE to implement jets.

It would be cleaner to enforce a trait for `J::Environment` which provides `c_jet_env` as a method.

**Comment by apoelstra** [comment]
Ok, I understand. We'll keep it as-is for now. It's not obvious that this method should be on `J::Environment` when plausibly the same environment type corresponds to different C environments, depending on the jet generic.

**Comment by apoelstra** [comment]
f98a088856008e1279eaadea75fd3d100965f4a1 is fine but you're not allowed to edit the Haskell-generated files directly like this.

**Comment by uncomputable** [comment]
Oops, I didn't realize that I am touching auto-generated files. I will make a PR to libsimplicity.

**Comment by uncomputable** [comment]
Depends on https://github.com/BlockstreamResearch/simplicity/pull/230

**Pull request closed without merging**
