### PR TITLE
Move witness unsharing from deserialization to finalization

### PR DESCRIPTION
**Pull request by apoelstra**
I think it makes more logical sense for witness nodes to be unshared during finalization (i.e. when witnesses are being attached to the program) rather than during deserialization (when unsharing is not always appropriate, leading to us having two `decode_program` methods, one which does unsharing and one which doesn't).

Better to deserialize a program without modifying it, and then only when attaching witnesses, make the appropriate decisions about how to do so. It is also dramatically simpler to do unsharing during finalization than it is to do it during deserialization.

### CODE REVIEW

**Comment by apoelstra** [comment]
Will leave this as a draft for a bit; there are other bugs I want to fix first.

**Comment by apoelstra** [comment]
This now builds on #98 and #100, and should be good to go once those two are in.

**Comment by apoelstra** [comment]
After this PR, and #104, I will change this so that `RedeemNode::finalize` has a choice of two iterators (a fully-shared one used when deserializing consensus programs, and a fully-unshared one used when constructing witnesses).

At that point there won't be any user-visible notion of "unsharing" at all.

**Comment by uncomputable** [comment]
I will review this tomorrow. Looks good at first glance and short.

**Comment by apoelstra** [comment]
Rebased.

**Comment by uncomputable** [comment]
One inconsistency is that `RedeemNode::decode()` enforces `1 → 1` but `CommitNode::finalize()` doesn't (see #105). We should address this in a follow-up PR.

**Comment by uncomputable** [comment]
ACK 226c2a8b240fe6fa9b18e525b9c65877dd3ab172.

**Review by uncomputable — APPROVED** [review]

**Pull request merged**
